# Generated by Django 3.2.20 on 2023-08-29 17:37

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
