# Generated by Django 3.2.20 on 2023-07-09 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(default='../default-profile.256x256_lpdl87', upload_to='images/')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('cities', models.TextField(default='Your favorite cities are...')),
                ('content', models.TextField(default='What kind of urban adventurer are you (food & drink lover, festival, sportif, wellness, etc)?Must visit cities, places to avoid, etc')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
