# Generated by Django 3.2.20 on 2023-07-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default-user-circle.256x256_qkk4wi', upload_to='images/'),
        ),
    ]
