# Generated by Django 3.2.20 on 2023-07-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(default='What kind of urban adventurer are you (food & drink lover,festival, sportif, wellness, etc)?Must visit cities, places to avoid, etc'),
        ),
    ]
