# Generated by Django 3.2.20 on 2023-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cities',
            field=models.TextField(default='My favorite cities are...'),
        ),
    ]
