# Generated by Django 3.2.20 on 2023-08-28 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TOUR_GUIDE', 'Tour guide'), ('ACCOMODATION', 'Accomodation'), ('RESTAURANT', 'Restaurant'), ('TRAVEL_AGENCY', 'Travel agency'), ('OTHER', 'Other'), ('SELECT_A_SERVICE_CATEGORY', 'Select a service category')], default='SELECT_A_SERVICE_CATEGORY', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='../handshake.256x176_vv06fu', upload_to='images/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
