# Generated by Django 3.2.20 on 2023-08-28 15:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
