# Generated by Django 3.2.20 on 2023-08-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230828_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_on']},
        ),
    ]
