# Generated by Django 3.2.20 on 2023-09-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='service',
            name='instagram_link',
        ),
    ]
